### ISSUE TITLE
Unable to load data after update - error: bad escape \p

### ISSUE THREAD

**Issue by tstreufert** [ranaroussi/pystore#24]
### Recently updated a number of packages and now can't load any of my items, with the same traceback each time.

Current versions:
python 3.7.3 in conda env
pystore  0.1.13
dask 2.3.0
pandas 0.25.1
fastparquet 0.3.2
numba 0.45.1
python-snappy 0.5.4

```python
In[24]: store.collection('Yahoo').item('adjClose')

Traceback (most recent call last):

  File "<ipython-input-24-c3f5c3720a65>", line 1, in <module>
    store.collection('Yahoo').item('adjClose')

  File "C:\Users\Tim\Anaconda3\lib\site-packages\pystore\collection.py", line 79, in item
    snapshot, filters, columns, engine=self.engine)

  File "C:\Users\Tim\Anaconda3\lib\site-packages\pystore\item.py", line 56, in __init__
    self._path, engine=self.engine, filters=filters, columns=columns)

  File "C:\Users\Tim\Anaconda3\lib\site-packages\dask\dataframe\io\parquet\core.py", line 155, in read_parquet
    **kwargs

  File "C:\Users\Tim\Anaconda3\lib\site-packages\dask\dataframe\io\parquet\fastparquet.py", line 173, in read_metadata
    fs, paths, gather_statistics, **kwargs

  File "C:\Users\Tim\Anaconda3\lib\site-packages\dask\dataframe\io\parquet\fastparquet.py", line 114, in _determine_pf_parts
    paths = fs.glob(paths[0] + fs.sep + "*")

  File "C:\Users\Tim\Anaconda3\lib\site-packages\fsspec\implementations\local.py", line 50, in glob
    return super().glob(path)

  File "C:\Users\Tim\Anaconda3\lib\site-packages\fsspec\spec.py", line 449, in glob
    pattern = re.compile(pattern.replace("=PLACEHOLDER=", '.*'))

  File "C:\Users\Tim\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "C:\Users\Tim\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "C:\Users\Tim\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "C:\Users\Tim\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "C:\Users\Tim\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "C:\Users\Tim\Anaconda3\lib\sre_parse.py", line 507, in _parse
    code = _escape(source, this, state)

  File "C:\Users\Tim\Anaconda3\lib\sre_parse.py", line 402, in _escape
    raise source.error("bad escape %s" % escape, len(escape))

error: bad escape \p

**Comment by tstreufert** [comment]
### Creating a new store from scratch gives a different error but looks like a similar section of dask/.../fastparquet.py 

```python
import pystore
import pandas as pd

df = pd.DataFrame([1,2,3,4], columns=['col'])

pystore.set_path('test')
store = pystore.store('test_store')
collection = store.collection('test_coll')
collection.write('test_item', df, overwrite=True)

print(collection.items)
Out: {'test_item'}

collection.item('test_item').data


Traceback (most recent call last):

  File "<ipython-input-2-27024044a983>", line 13, in <module>
    collection.item('test_item').data

  File "C:\Users\Tim\Anaconda3\lib\site-packages\pystore\collection.py", line 79, in item
    snapshot, filters, columns, engine=self.engine)

  File "C:\Users\Tim\Anaconda3\lib\site-packages\pystore\item.py", line 56, in __init__
    self._path, engine=self.engine, filters=filters, columns=columns)

  File "C:\Users\Tim\Anaconda3\lib\site-packages\dask\dataframe\io\parquet\core.py", line 155, in read_parquet
    **kwargs

  File "C:\Users\Tim\Anaconda3\lib\site-packages\dask\dataframe\io\parquet\fastparquet.py", line 173, in read_metadata
    fs, paths, gather_statistics, **kwargs

  File "C:\Users\Tim\Anaconda3\lib\site-packages\dask\dataframe\io\parquet\fastparquet.py", line 115, in _determine_pf_parts
    base, fns = _analyze_paths(paths, fs)

  File "C:\Users\Tim\Anaconda3\lib\site-packages\dask\dataframe\io\parquet\utils.py", line 406, in _analyze_paths
    basepath = path_parts_list[0][:-1]

IndexError: list index out of range

**Comment by tstreufert** [comment]
#### Update: downgrading dask from 2.3.0 ==> 2.1.0 has solved the issue. No other packages modified.

**Comment by ranaroussi** [comment]
Closing for now. Will reopen if problem resurfaces
